wallet/config/routes.rb
Rails.application.routes.draw do
  resources :exchanges

  root 'exchanges#index'
  get 'exchanges/index'
  post 'exchanges/index'

end

wallet/app/models/exchange.rb
class Exchange < ActiveRecord::Base

  def self.balance
    self.all.reduce(0.0) {|sum, i| sum + i.amount}
  end

  def self.transactions
    self.count
  end

  def self.current_monthly_spendings
    current_monthly_spendings = []
    self.all.each do |c|
      current_monthly_spendings << c.amount if c.amount < 0 && (Time.now.mon == c.created_at.mon)
    end
    current_monthly_spendings = current_monthly_spendings.reduce(0.0) {|sum, c| sum += c}
  end

  def self.last_months_spendings
    last_months_spendings = []
    self.all.each do |c|
      last_months_spendings << c.amount if c.amount < 0 && ((Time.now.mon - 1) == c.created_at.mon)
    end
    last_months_spendings = last_months_spendings.reduce(0.0) {|sum, c| sum += c}
  end

  def self.total_monthly_transactions
    total_monthly_transactions = []
    self.all.each do |c|
      total_monthly_transactions << c.amount if (Time.now.mon == c.created_at.mon)
    end
    total_monthly_transactions = total_monthly_transactions.reduce(0.0) {|sum, c| sum += c}
  end

  def self.total_last_months_transactions
    total_last_months_transactions = []
    self.all.each do |c|
      total_last_months_transactions << c.amount if ((Time.now.mon - 1) == c.created_at.mon)
    end
    total_last_months_transactions = total_last_months_transactions.reduce(0.0) {|sum, c| sum += c}

  end

  def self.largest_current_month
    largest_current_month = []
    self.all.each do |c|
      largest_current_month << c.amount if (Time.now.mon == c.created_at.mon)
    end
    largest_current_month.max
  end

  def self.largest_total_expense

  end


  # def self.list_of_transactions
  #   array = []
  #   self.all.each do |t|
  #     array << t
  #   end
  #   array
  # end
end

wallet/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

wallet/app/controllers/exchanges_controller.rb
class ExchangesController < ApplicationController
  before_action :set_exchange, only: [:show, :edit, :update, :destroy]

  # GET /exchanges
  # GET /exchanges.json
  def index
    @exchanges = Exchange.all
    @transactions = Exchange.transactions
    @balance = Exchange.balance
    @current_monthly_spendings = Exchange.current_monthly_spendings
    @last_months_spendings = Exchange.last_months_spendings
    @total_monthly_transactions = Exchange.total_monthly_transactions
    @total_last_months_transactions = Exchange.total_last_months_transactions
    @largest_current_month = Exchange.largest_current_month
    if @balance < 0
      flash[:notice] = "Hey Bozo, you broke as a yolk."
    end
    # @list_of_transactions = Exchange.list_of_transactions
  end

  # GET /exchanges/1
  # GET /exchanges/1.json
  def show
  end

  # GET /exchanges/new
  def new
    @exchange = Exchange.new
  end

  # GET /exchanges/1/edit
  def edit
  end

  # POST /exchanges
  # POST /exchanges.json
  def create
    @exchange = Exchange.new(exchange_params)

    respond_to do |format|
      if @exchange.save
        format.html { redirect_to @exchange, notice: 'Exchange was successfully created.' }
        format.json { render :show, status: :created, location: @exchange }
      else
        format.html { render :new }
        format.json { render json: @exchange.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exchanges/1
  # PATCH/PUT /exchanges/1.json
  def update
    respond_to do |format|
      if @exchange.update(exchange_params)
        format.html { redirect_to @exchange, notice: 'Exchange was successfully updated.' }
        format.json { render :show, status: :ok, location: @exchange }
      else
        format.html { render :edit }
        format.json { render json: @exchange.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exchanges/1
  # DELETE /exchanges/1.json
  def destroy
    @exchange.destroy
    respond_to do |format|
      format.html { redirect_to exchanges_url, notice: 'Exchange was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exchange
      @exchange = Exchange.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exchange_params
      params.require(:exchange).permit(:amount, :recipient)
    end
end

wallet/app/helpers/application_helper.rb
module ApplicationHelper
end

wallet/app/helpers/exchanges_helper.rb
module ExchangesHelper
end

wallet/app/views/exchanges/_form.html.erb
<%= form_for(@exchange) do |f| %>
  <% if @exchange.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exchange.errors.count, "error") %> prohibited this exchange from being saved:</h2>

      <ul>
      <% @exchange.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :recipient %><br>
    <%= f.text_field :recipient %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

wallet/app/views/exchanges/edit.html.erb
<h1>Editing Exchange</h1>

<%= render 'form' %>

<%= link_to 'Show', @exchange %> |
<%= link_to 'Back', exchanges_path %>

wallet/app/views/exchanges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Exchanges</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Recipient</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exchanges.each do |exchange| %>
      <tr>
        <td><%= exchange.amount %></td>
        <td><%= exchange.recipient %></td>
        <td><%= link_to 'Show', exchange %></td>
        <td><%= link_to 'Edit', edit_exchange_path(exchange) %></td>
        <td><%= link_to 'Destroy', exchange, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exchange', new_exchange_path %>

<p>Total transactions is <%=@transactions%></p>
<!-- <p>Total list_of_transactions is <%=@list_of_transactions%></p> -->
<p>Total balance <%=@balance%></p>
<p>Total current_monthly_spendings <%=@current_monthly_spendings%></p>
<p>Total last_months_spendings <%=@last_months_spendings%></p>
<p>Total total_monthly_transactions <%=@total_monthly_transactions%></p>
<p>Total total_last_months_transactions <%@total_last_months_transactions%></p>
<p>Total largest_current_month <%@largest_current_month%></p>

wallet/app/views/exchanges/new.html.erb
<h1>New Exchange</h1>

<%= render 'form' %>

<%= link_to 'Back', exchanges_path %>

wallet/app/views/exchanges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @exchange.amount %>
</p>

<p>
  <strong>Recipient:</strong>
  <%= @exchange.recipient %>
</p>

<%= link_to 'Edit', edit_exchange_path(@exchange) %> |
<%= link_to 'Back', exchanges_path %>

wallet/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wallet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>